import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent
START_MARKER = "// PHOTO_URLS_START"
END_MARKER = "// PHOTO_URLS_END"
ALLOWED_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}


def build_photo_block(photo_files: list[Path], index_dir: Path) -> str:
    lines = [f"{START_MARKER} (auto-generated by generate_photo_list.py)", "const photoUrls = ["]
    for file_path in photo_files:
        rel = file_path.relative_to(index_dir).as_posix()
        lines.append(f'  "{rel}",')
    lines.append("];")
    lines.append(END_MARKER)
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Auto-generate photoUrls list inside Index.html."
    )
    parser.add_argument(
        "--index",
        default="Index.html",
        help="Path to Index.html (default: Index.html)",
    )
    parser.add_argument(
        "--photo-dir",
        default="foto",
        help="Path to photo folder (default: foto)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    index_path = (ROOT / args.index).resolve() if not Path(args.index).is_absolute() else Path(args.index).resolve()
    photo_dir = (ROOT / args.photo_dir).resolve() if not Path(args.photo_dir).is_absolute() else Path(args.photo_dir).resolve()

    if not index_path.exists():
        raise FileNotFoundError(f"Index file not found: {index_path}")
    if not photo_dir.exists():
        raise FileNotFoundError(f"Photo folder not found: {photo_dir}")
    if not photo_dir.is_dir():
        raise NotADirectoryError(f"Photo path is not a directory: {photo_dir}")

    photo_files = sorted(
        (p for p in photo_dir.iterdir() if p.is_file() and p.suffix.lower() in ALLOWED_EXT),
        key=lambda p: p.name.lower(),
    )

    index_dir = index_path.parent
    try:
        for p in photo_files:
            p.relative_to(index_dir)
    except ValueError as exc:
        raise ValueError(
            "Photo folder must be under the same drive/root as Index.html to build relative URLs."
        ) from exc

    html = index_path.read_text(encoding="utf-8")
    start = html.find(START_MARKER)
    end = html.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise ValueError("Markers not found in Index.html.")

    end_line = html.find("\n", end)
    if end_line == -1:
        end_line = len(html)
    else:
        end_line += 1

    new_block = build_photo_block(photo_files, index_dir) + "\n"
    updated_html = html[:start] + new_block + html[end_line:]
    index_path.write_text(updated_html, encoding="utf-8")

    print(f"Updated photo list with {len(photo_files)} file(s) in {index_path}.")


if __name__ == "__main__":
    main()
