from pathlib import Path


ROOT = Path(__file__).resolve().parent
INDEX_PATH = ROOT / "Index.html"
PHOTO_DIR = ROOT / "foto"
START_MARKER = "// PHOTO_URLS_START"
END_MARKER = "// PHOTO_URLS_END"
ALLOWED_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}


def build_photo_block(photo_files: list[Path]) -> str:
    lines = [f"{START_MARKER} (auto-generated by generate_photo_list.py)", "const photoUrls = ["]
    for file_path in photo_files:
        rel = file_path.relative_to(ROOT).as_posix()
        lines.append(f'  "{rel}",')
    lines.append("];")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main() -> None:
    if not INDEX_PATH.exists():
        raise FileNotFoundError(f"Index file not found: {INDEX_PATH}")
    if not PHOTO_DIR.exists():
        raise FileNotFoundError(f"Photo folder not found: {PHOTO_DIR}")

    photo_files = sorted(
        (p for p in PHOTO_DIR.iterdir() if p.is_file() and p.suffix.lower() in ALLOWED_EXT),
        key=lambda p: p.name.lower(),
    )

    html = INDEX_PATH.read_text(encoding="utf-8")
    start = html.find(START_MARKER)
    end = html.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise ValueError("Markers not found in Index.html.")

    end_line = html.find("\n", end)
    if end_line == -1:
        end_line = len(html)
    else:
        end_line += 1

    new_block = build_photo_block(photo_files) + "\n"
    updated_html = html[:start] + new_block + html[end_line:]
    INDEX_PATH.write_text(updated_html, encoding="utf-8")

    print(f"Updated photo list with {len(photo_files)} file(s).")


if __name__ == "__main__":
    main()
